### PR TITLE
[KDEV-22074] Upgrades mocha for growl dependency security vulnerability

### PR DESCRIPTION
**Pull request by aefritz19**
Upgrades Mocha to handle growl security vulnerability. This change [does not impact tests](https://share.getcloudapp.com/QwubbgxY).

See https://kustomer.atlassian.net/browse/KDEV-22074

### CODE REVIEW

**Comment by obukspan** [comment]
@aefritz19 curious if the tests still pass locally (despite not having CI configured)?

also potential question for @kustomer/trust (since that's been the bulk of the contributions here) – should we bump our version to 3.0.1 and also update it in api?  https://github.com/kustomer/api/blob/master/package.json#L10

Doesn't look like this impacts anything functional.

Also can probably remove the `build_test_deploy` status check.

**Comment by aefritz19** [comment]
@obukspan Oh yeah, adding screenshot in the description

**Review by obukspan — DISMISSED** [review]

**Comment by obukspan** [comment]
@joeyfromspace if you have 2 min would be curious to get your thoughts here on whether we should make a habit of bumping the version / release process for changes to multer.

**Comment by joeyfromspace** [comment]
@obukspan I think after we merge, we just have to create a new tag here in github, then reference the new tag in api's `package.json`. Though the tag version should _probably_ match the version in this repo's `package.json`?

https://github.com/kustomer/api/blob/master/package.json#L9-L10

**Comment by aefritz19** [comment]
@obukspan @joeyfromspace Should I bump with this current PR? I'm also blocked by the `build_test_deploy`.

**Comment by obukspan** [comment]
Sorry I missed this! need to fix my github notifs.

@aefritz19 I updated the `build_test_deploy` piece.

I would recommend bumping the version in this PR and once it's merged we'll create the matching release.

**Comment by aefritz19** [comment]
@obukspan Bumped to 3.0.1. Just needs another pass so I can merge.

**Review by obukspan — APPROVED** [review]
thanks!

**Pull request merged**
